### ISSUE TITLE
pytorch-autocomplete as a service

### ISSUE THREAD

**Issue by ghost** [christophmark/pytorch-autocomplete#1]
Hi Christoph,

Hope you are doing all well !

I was wondering how complicated it would be to update pytorch-autocomplete as a service with guincorn/flask ?

I am a newbie in python, much more a gopher, and was wondering if I can ask you some help. I would like to test it on a website I am working on http://paper2code.com/

Have a great day !

Cheers,
X

**Comment by christophmark** [comment]
Hi x0rzkov,

thanks for the interest in the project. For serving trained Pytorch models, have a look at https://pytorch.org/serve/

Unfortunately, I currently do not have spare time to consult on this project.

Cheers,
Chris
